no_of_acc = ("savings", "current", "fixed", "credit","current", "fixed", "credit")
print(type(no_of_acc), no_of_acc)
print("total  number of values in tuple is: ", len(no_of_acc))
for i in no_of_acc:
    print(i)
print("*"*65)
print("no of times credit is printd:",no_of_acc.count("credit"))
print("to know the index value", no_of_acc.index("fixed"))
print("to know the index value", no_of_acc.index("fixed",3))
print("display in reverse formate:",no_of_acc[::-1])
print("slicing from 1 to 3:", no_of_acc[1:4])
print("sorting the tuple :",tuple(sorted(no_of_acc)))
s_acc = tuple(sorted(no_of_acc))
print("diplaying reverse after sorting :", s_acc[::-1])
t_acc = ("alladin")
print("this will display string type:",type(t_acc))
t_acc = ("alladin",)
print("this will display tuple type just bcz we gave ,:",type(t_acc))

